<template>
    <div>
        <shop-list-item></shop-list-item>
        <shop-list-item></shop-list-item>
        <shop-list-item></shop-list-item>
        <shop-list-item></shop-list-item>
        <shop-list-item></shop-list-item>
    </div>
</template>